# Copy this file to you project's root directory (containing the project.json)
# then update the variables and paths trigger as a appropriate.
#
# The resouces section points to the repository containing the pipeline templates. This is set to UiPath's repository.
# DO NOT use the UiPath template repository for anything other than testing. It may change without notice.
# Please fork/replicate this repository to host it yourself and make any required modifications.

variables:
  # The full path to the folder containing the project.json file for this pipeline
  projectPath: MyProject
  # The name of the folder to deploy the package to.
  folderName: Default
  # Either AutoVersion to generate a build number or CurrentVersion to match the project.json version.
  versioningStrategy: CurrentVersion
  # The orchestrator tenant to deploy to. Not used, but may be useful if deploying to multiple tenants.
  tenant: Default
  # The environments to update the package version to the deployed version. 
  # Not required for modern folders or if you do not want to update the package version.
  environments: ''

# Update this trigger to specify when the pipeline should run.
# Variables cannot be used here.
trigger:
  # Define what branches trigger the pipeline
  branches:
    include:
      - master    # Will push to Prod after approval
      - release*  # Will push to Test without approval
  # Define what paths to include for building this pipeline. Normally, you should add the same projectPath as above,
  # so that any change to the project will trigger the pipeline, but it will ignore any changes to other projects.
  paths:
    include:
      - MyProject/*  # Update this

# This points to the repository containing the templates. Update this to point to your template repository.
resources:
  repositories:
    - repository: templates
      type: github  # use 'git' for a repo hosted in Azure DevOps
      endpoint: my-github-service-connection
      name: UiPath-US-Services/uipath-azure-pipeline-templates

# Use the specified template. 
extends:
  template: project-pipeline-template.yaml@templates  # Template reference
  parameters:
    projectPath: $(projectPath)
    folderName: $(folderName)
    versioningStrategy: $(versioningStrategy)
    environments: $(environments)
